// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpBjGwklguWPpN8f1Ihx-jRc2Hw9zEQh4',
    appId: '1:709030195522:web:f843e2b4efb28635cc98db',
    messagingSenderId: '709030195522',
    projectId: 'pembinaan-7408d',
    authDomain: 'pembinaan-7408d.firebaseapp.com',
    storageBucket: 'pembinaan-7408d.appspot.com',
    measurementId: 'G-9Z9YEPLZ1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIX1WEm-2rTCXedY6kfBrG7etZXa97nw',
    appId: '1:709030195522:android:91843c14e1f0ea90cc98db',
    messagingSenderId: '709030195522',
    projectId: 'pembinaan-7408d',
    storageBucket: 'pembinaan-7408d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKpCzldvoaCGQIZpbmu7fhRFTYhnb5s0E',
    appId: '1:709030195522:ios:b6694449e2ff7242cc98db',
    messagingSenderId: '709030195522',
    projectId: 'pembinaan-7408d',
    storageBucket: 'pembinaan-7408d.appspot.com',
    iosBundleId: 'com.example.frontend2',
  );
}
